# Generated by Django 3.2 on 2021-04-28 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['event_date'], 'verbose_name': 'event', 'verbose_name_plural': 'events'},
        ),
        migrations.AlterField(
            model_name='event',
            name='amount_of_visitors',
            field=models.IntegerField(default=0),
        ),
    ]
