# Generated by Django 3.2 on 2021-04-28 14:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20210428_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='amount_of_visitors',
        ),
        migrations.AddField(
            model_name='event',
            name='visitors',
            field=models.ManyToManyField(related_name='visitors', to=settings.AUTH_USER_MODEL),
        ),
    ]
